#!/bin/sh
# Tomcat server auto-start script

export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64

 

case $1 in
start)
sh /usr/local/tomcat/bin/startup.sh
;;
stop)
sh /usr/local/tomcat/bin/shutdown.sh
;;
restart)
sh /usr/local/tomcat/bin/shutdown.sh
sh /usr/local/tomcat/bin/startup.sh
;;
esac
exit 0

